#!/bin/bash

# running from module directory
logger="[DEPTRIM]"
mkdir original
cp pom.xml pom-original.xml 
echo "${logger} Building original project and storing data"
cp pom.xml original/pom-original.xml
mvn clean package >> original/maven.log
cp target/*.jar original/
mvn dependency:tree >> original/dependency-tree.log

echo "====================================================="
echo "${logger} Running DepTrim"
echo "====================================================="
mvn se.kth.castor:deptrim-maven-plugin:0.0.1:deptrim -DcreatePomTrimmed=true -DignoreScopes=test,provided,system,import,runtime
cp -r target/dependency original/
cp -r libs-deptrim original/

poms=`find . -name "pom-debloated-spl-*.xml" | wc -l`
echo "${logger} Number of poms generated by DepTrim: ${poms}"

for i in $(seq ${poms})
do
  echo "${logger} Working with pom-debloated-spl-"${i}".xml"
  output=pom-${i}
  mkdir ${output}
  cp pom-debloated-spl-${i}.xml ${output}/
  # Setting as main pom
  mv pom-debloated-spl-${i}.xml pom.xml
  # Running mvn clean package
  mvn clean package >> ${output}/maven.log
  mvn dependency:tree >> ${output}/dependency-tree.log
  cp target/*.jar ${output}/
  # Restoring pom number
  mv pom.xml pom-debloated-spl-${i}.xml
done

# Restore original pom
echo "${logger} Restoring original pom and exiting"
mv pom-original.xml pom.xml
